### ISSUE TITLE
Using * wildcard no longer works

### ISSUE THREAD

**Issue by zacanger** [koajs/router#76] opened 2020-04-14 21:34 UTC
node.js version: 12.6.1

npm/yarn and version: npm 6.14.4

`@koa/router` version: 9.0.0

`koa` version: 2.11.0

#### Code sample:

```js
const Koa = require('koa')
const Router = require('@koa/router')

const app = new Koa()
const router = new Router()
const port = 8000

router.get('*', (ctx) => {
  ctx.body = 'hello'
})

app.use(router.routes())

app.listen(port, () => {
  console.log(`listening on ${port}`)
})
```

#### Expected Behavior:

App should not crash

#### Actual Behavior:

App crashes:

```~/.tmp/1586900133 node index.js
/home/z/.tmp/1586900133/node_modules/path-to-regexp/dist/index.js:113
        throw new TypeError("Unexpected " + nextType + " at " + index + ", expected " + type);
        ^

TypeError: Unexpected MODIFIER at 0, expected END
    at mustConsume (/home/z/.tmp/1586900133/node_modules/path-to-regexp/dist/index.js:113:15)
    at parse (/home/z/.tmp/1586900133/node_modules/path-to-regexp/dist/index.js:172:9)
    at stringToRegexp (/home/z/.tmp/1586900133/node_modules/path-to-regexp/dist/index.js:329:27)
    at pathToRegexp (/home/z/.tmp/1586900133/node_modules/path-to-regexp/dist/index.js:403:12)
    at new Layer (/home/z/.tmp/1586900133/node_modules/@koa/router/lib/layer.js:48:17)
    at Router.register (/home/z/.tmp/1586900133/node_modules/@koa/router/lib/router.js:578:15)
    at Router.<computed> [as get] (/home/z/.tmp/1586900133/node_modules/@koa/router/lib/router.js:203:12)
    at Object.<anonymous> (/home/z/.tmp/1586900133/index.js:8:8)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
```

I believe the path-to-regexp upgrade in #71 broke this. The use case here is, for example, SSR on any route that doesn't match a previously defined one.

**Comment by niftylettuce** [comment] 2020-04-14 21:49
Ping @Sinewyk @tigt -- can you resolve/PR?

**Comment by Sinewyk** [comment] 2020-04-14 22:38
Not a bug, it's a feature :trollface:

For real though: it's a breaking change inside `path-to-regexp`

https://github.com/pillarjs/path-to-regexp#compatibility-with-express--4x
> No wildcard asterisk (`*`) - use parameters instead (`(.*)` or `:splat*`)

**Comment by zacanger** [comment] 2020-04-14 22:40
Ah, thank you! Would it be worth documenting that in this repo's changelog, since it is technically a breaking change?

**Comment by Sinewyk** [comment] 2020-04-14 22:48
It is marked as a breaking change: which is why it's `9.0.0` and not `8.1.0` 😎 

But yeah, probably a note in the readme to underline breaking changes in the path-to-regexp library with a link to it or something, why not.

**Comment by niftylettuce** [comment] 2020-04-14 22:50
If anyone submits a PR with notice I would merge

**Comment by zacanger** [comment] 2020-04-14 22:56
Thanks folks!

**Closed** 2020-04-14 22:55 UTC

**Comment by HermanLederer** [comment] 2022-03-22 23:02
Seems the issue arose again.

The following code results in the same error. `Unexpected MODIFIER at 0, expected END`
```ts
router.get('*', async (ctx) => {}
```

The following code works fine
```ts
router.get(/.*/, async (ctx) => {}
```

**Comment by jmanzo** [comment] 2022-08-30 18:47
Hey, sup guys? If any of you still have the same issue, I got it working:

`router.get(`/subpath/:splat*`, verifierMiddleware);`

Just in case you're facing the same exact issue I did.

**Comment by iamgabrielsoft** [comment] 2023-01-09 04:08
> Seems the issue arose again.
> 
> The following code results in the same error. `Unexpected MODIFIER at 0, expected END`
> 
> ```ts
> router.get('*', async (ctx) => {});
> ```
> 
> The following code works fine
> 
> ```ts
> router.get(/.*/, async (ctx) => {});
> ```
> 
> Dependencies:
> 
> ```json
> {
>     "koa": "^2.13.4",
>     "koa-router": "^10.1.1"
> }
> ```

this still doesn't work in 2023

**Comment by gengjiawen** [comment] 2023-04-26 07:19
If you want to use `router.get(/.*/, async (ctx) => {});`, it has to be the root router, not having any prefix.
