### ISSUE TITLE
The ctx. _matchedRoute is not the match route.

### ISSUE THREAD

**Issue by BainDragneel** [koajs/router#34] opened 2019-11-04 06:49 UTC
node.js version: v13.0.1

npm/yarn and version: 6.12.0 

`koa-router` version: 7.4.0  and i tried @koa/router v8.0.2, too.

`koa` version: 2.7.0

#### Code sample:

Now I have two routes, one is "/api/order/list" and another is "/api/order/:orderId" ,

```js
const Router = require("koa-router");
const router = new Router({
    "prefix": "/api",
});
router.get('/order/list',controller.getOrderList);
router.get('/order/:orderId',controller.getOrder);

```
I want to log each request.I want the url I am recording to be the url of my own defined api, not the url directly with params.For example, when I request "http://127.0.0.1:3000/api/order/57d52c52403f2ee865738ec7", I want to record that the url is "/api/order/:orderId" instead of "/api/order/57d52c52403f2ee865738ec7",And   when I request "http://127.0.0.1:3000/api/order/list", I want to record that the url is "/api/order/list" instead of "/api/order/:orderId".
But ctx. _matchedRoute is not the route I requested.
#### Expected Behavior:

when I request "http://127.0.0.1:3000/api/order/list", ctx. _matchedRoute is "/api/order/:orderId"
#### Actual Behavior:

ctx. _matchedRoute is "/api/order/list"
#### Additional steps, HTTP request details, or  to reproduce the behavior or a test case:
i have the four screenshots.

## http:127.0.0.1:3000/api/order/list
![image](https://user-images.githubusercontent.com/47975259/68103415-ab00e400-ff11-11e9-8afa-d32276e75f25.png)
ctx.matched
![image](https://user-images.githubusercontent.com/47975259/68103417-b0f6c500-ff11-11e9-8f4f-aaf8c1c2934e.png)

## http:127.0.0.1:3000/api/order/:orderId
![image](https://user-images.githubusercontent.com/47975259/68103461-ed2a2580-ff11-11e9-9028-e78f4b97c441.png)
ctx.matched
![image](https://user-images.githubusercontent.com/47975259/68103474-f74c2400-ff11-11e9-9844-c91b4046c250.png)

**Comment by niftylettuce** [comment] 2019-12-23 06:56
Can you submit a PR that has a failing test case?  This is a good find, thank you!

**Comment by kroleg** [comment] 2020-01-20 09:08
This is not a bug, it's a feature (kind of). Here is `@koa/router` code (lib/router.js:342):
```js
var mostSpecificLayer = matchedLayers[matchedLayers.length - 1]
ctx._matchedRoute = mostSpecificLayer.path;
if (mostSpecificLayer.name) {
  ctx._matchedRouteName = mostSpecificLayer.name;
}
```
@BainDragneel in your case matchedLayers look like: [`/`, `/order/list`, `/order/:orderId`] and `/order/:orderId` is just most specific route. 
You may specifiy regexp for `id` param like `/order/:orderId/:id([0-9]+)` but in this case _matchedRoute will equal to `/order/:orderId/:id([0-9]+)` for url `/order/57d52c52403f2ee865738ec7`

I can think of better solution. Express allows to specifiy regexp restriction for route param like `router.param('orderId', /d+/)`. koa router's `.param` can also accept regexp as second param like 
`.param('orderId', /\d+/, handleOrderIdParam)` @niftylettuce i can work on a PR implementing this

**Comment by falkenhawk** [comment] 2020-06-30 12:31
@kroleg This is a bug, see https://github.com/ZijianHe/koa-router/labels/first%20matched%20route
The **first** matched route should be used for executing its and only its middlewares. (not the last, not the most generic, etc. and definitely not multiple routes - I cannot imagine a case when executing multiple routes per one request would be a desirable and expected result)

Allegedly it was fixed on the original repo for "8.x branch": https://github.com/ZijianHe/koa-router/issues/231#issuecomment-392974584
- https://github.com/ZijianHe/koa-router/blob/c0e9e088cd679f3c4030b73d8c0fc7b69e1ffecb/test/matched.test.js#L64-L73
- as worked on the `8.x` branch: https://github.com/ZijianHe/koa-router/commits/8.x
- and released as `v8.0.0-alpha.1` https://www.npmjs.com/package/koa-router/v/8.0.0-alpha.1:
but then it must have been lost somewhere along the transition to this repo, as the works on `8.x` were completely discarded and instead `v8.0.0` was released with just a package name change:
https://github.com/koajs/router/commit/94698a3231ab76e16c80579210a4609bdc3cc629
(And btw the unfinished `8.x` branch still exists on this forked repo: https://github.com/koajs/router/commits/8.x)

I am currently on `@koa/router` v9.0.1 and still multiple sets of middlewares are executed when multiple paths are "matched", instead just stopping at the first path matched.

And there was also that PR on the original repo which stalled and got closed https://github.com/ZijianHe/koa-router/pull/345 (possibly before the v8.x rewrite). Maybe that could be based on to fix this bug.

I am not asking to continue working on the 8.x branch, but only to acknowledge this issue (as reported here and in multiple issues on the original repo) as a real bug and unintended behaviour. That might hopefully encourage someone with enough time at hand to pick it up and file a PR.

**Comment by niftylettuce** [comment] 2020-06-30 12:40
If anyone makes a PR I will award them a bug bounty, payable over PayPal.

**Comment by falkenhawk** [comment] 2020-06-30 13:03
@niftylettuce I've found this PR on the original repo which possibly fixes this issue: https://github.com/ZijianHe/koa-router/pull/525 and also something somewhat related: https://github.com/ZijianHe/koa-router/pull/492

**Comment by niftylettuce** [comment] 2020-06-30 13:54
Can someone review @mdenisov PR #93? cc @falkenhawk 

@mdenisov if you're confident about it lmk

**Comment by mdenisov** [comment] 2020-06-30 14:07
@niftylettuce I transferred this [PR](https://github.com/ZijianHe/koa-router/pull/525) from the original repo and this fix solves this problem. Works great on my project :)

**Comment by niftylettuce** [comment] 2020-06-30 16:44
@mdenisov can you please send me your PayPal or preferred means of receiving a donation for your bug bounty award here?  niftylettuce@gmail.com

**Closed** 2020-06-30 16:43 UTC

**Comment by mdenisov** [comment] 2020-06-30 16:52
@niftylettuce It is not necessary, thanks :)

**Comment by BainDragneel** [comment] 2020-08-07 10:55
Thanks very much, I have some things I did not pay attention to this issue in time, sorry!
